const Images = {
  Logo: require('../assets/images/Logo.png'),
  Notifications: require('../assets/images/Notifications.png'),
  User: require('../assets/images/User.png'),
  Edit: require('../assets/images/Edit.png'),
  IconMyChannel: require('../assets/images/IconMyChannel.png'),
  IconSubscriptions: require('../assets/images/IconSubscriptions.png'),
  IconPaymentMethods: require('../assets/images/IconPaymentMethods.png'),
  IconProfile: require('../assets/images/IconProfile.png'),
  IconNotfications: require('../assets/images/IconNotfications.png'),
  IconPreferences: require('../assets/images/IconPreferences.png'),
  IconSecurity: require('../assets/images/IconSecurity.png'),
  IconLanguages: require('../assets/images/IconLanguages.png'),
  IconDarkMode: require('../assets/images/IconDarkMode.png'),
  IconHelp: require('../assets/images/IconHelp.png'),
  IconInvite: require('../assets/images/IconInvite.png'),
  IconCommunity: require('../assets/images/IconCommunity.png'),
  IconTerms: require('../assets/images/IconTerms.png'),
  IconAbout: require('../assets/images/IconAbout.png'),
  IconLogout: require('../assets/images/IconLogout.png'),
  Games: require('../assets/images/Games.png'),
  LastStream: require('../assets/images/LastStream.png'),
  Video: require('../assets/images/Video.png'),
  Avatar: require('../assets/images/Avatar.jpeg'),
  RCB2020: require('../assets/images/RCB2020.png'),
  PFBanner1: require('../assets/images/PFBanner1.png'),
  JoelMottLaK153ghdigUnsplash: require('../assets/images/JoelMottLaK153ghdigUnsplash.jpg'),
  JakubKapusnak1TkhHPOubu4Unsplash: require('../assets/images/JakubKapusnak1TkhHPOubu4Unsplash.jpg'),
  IndAusDay1: require('../assets/images/IndAusDay1.png'),
  TeamIndiaHoliCelebration2023: require('../assets/images/TeamIndiaHoliCelebration2023.jpeg'),
  TeamIndHoli2023: require('../assets/images/TeamIndHoli2023.png'),
  Sendmsg: require('../assets/images/Sendmsg.png'),
  Camera: require('../assets/images/Camera.png'),
  Gallery: require('../assets/images/Gallery.png'),
  File: require('../assets/images/File.png'),
  Location: require('../assets/images/Location.png'),
  Audio: require('../assets/images/Audio.png'),
  Contact: require('../assets/images/Contact.png'),
  IndAus4thTest: require('../assets/images/IndAus4thTest.png'),
  KKRVsMI: require('../assets/images/KKRVsMI.png'),
  MatchScoreSnap: require('../assets/images/MatchScoreSnap.png'),
  BANBatting: require('../assets/images/BANBatting.png'),
  ENGBatting: require('../assets/images/ENGBatting.png'),
  Toss: require('../assets/images/Toss.png'),
  POM: require('../assets/images/POM.png'),
  RohitToss: require('../assets/images/RohitToss.png'),
  RohitSix: require('../assets/images/RohitSix.png'),
  KKRLogo: require('../assets/images/KKRLogo.png'),
  PFLogin: require('../assets/images/PFLogin.png'),
  PFbanner2: require('../assets/images/PFbanner2.png'),
  PFbanner3: require('../assets/images/PFbanner3.png'),
  JonathanBorbaKgCSRo4SiT8Unsplash: require('../assets/images/JonathanBorbaKgCSRo4SiT8Unsplash.jpg'),
  MalikSkydsgaardIgkwHPbVk8Unsplash: require('../assets/images/MalikSkydsgaardIgkwHPbVk8Unsplash.jpg'),
  AndreTaissin5OUMf1Mr5pUUnsplash: require('../assets/images/AndreTaissin5OUMf1Mr5pUUnsplash.jpg'),
  LolaRoseZcHseJqAeEcUnsplash: require('../assets/images/LolaRoseZcHseJqAeEcUnsplash.jpg'),
  Ellipse21: require('../assets/images/Ellipse21.png'),
  EditProfile: require('../assets/images/EditProfile.png'),
  PfBanner4: require('../assets/images/PfBanner4.png'),
  Fbicon: require('../assets/images/Fbicon.png'),
  Insta: require('../assets/images/Insta.png'),
  Twitter: require('../assets/images/Twitter.png'),
  _27iplChikas: require('../assets/images/27iplChikas.png'),
  Mic1: require('../assets/images/Mic1.jpeg'),
  ProfileCover: require('../assets/images/ProfileCover.png')
}

export const RemoteAvatars = [
  'https://pvbtcdjiibcaleqjdrih.supabase.co/storage/v1/object/public/user-bucket/avatars/avatar_0.png',
  'https://pvbtcdjiibcaleqjdrih.supabase.co/storage/v1/object/public/user-bucket/avatars/avatar_1.png',
  'https://pvbtcdjiibcaleqjdrih.supabase.co/storage/v1/object/public/user-bucket/avatars/avatar_2.png',
  'https://pvbtcdjiibcaleqjdrih.supabase.co/storage/v1/object/public/user-bucket/avatars/avatar_3.png',
  'https://pvbtcdjiibcaleqjdrih.supabase.co/storage/v1/object/public/user-bucket/avatars/avatar_4.png',
  'https://pvbtcdjiibcaleqjdrih.supabase.co/storage/v1/object/public/user-bucket/avatars/avatar_5.png',
  'https://pvbtcdjiibcaleqjdrih.supabase.co/storage/v1/object/public/user-bucket/avatars/avatar_6.png',
  'https://pvbtcdjiibcaleqjdrih.supabase.co/storage/v1/object/public/user-bucket/avatars/avatar_7.png',
  'https://pvbtcdjiibcaleqjdrih.supabase.co/storage/v1/object/public/user-bucket/avatars/avatar_8.png',
]

export default Images
